### ISSUE TITLE
Creating many new/ empty projects kills the app

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1257] opened 2016-12-22 18:21 UTC
1. Just hit + in projects many times
2. say order by kind
3. try to go back to by project 
-> idels indefinitely

![Screen Shot 2016-12-22 at 10.20.52 AM.png](https://zube.io/files/Autodesk/a5169c2f22c15085cd576d0761efd960.png)

**Comment by cojofra** [comment] 2017-01-03 21:24
max tested on db one - may go away upon merge

**Comment by duncanmeech** [comment] 2017-01-04 22:12
This was probably related to another rendering bug I just fixed in another PR. I tested and can't reproduce even using the keyboard shortcut held down.

**Closed** 2017-01-06 19:51 UTC
Labels: bug:broken_tools
